### ISSUE TITLE
Any update for TTGO T-Beam V1.1?

### ISSUE THREAD

**Issue by geronimoooooooo** [HikariBoy/TTGO-Tbeam-Ultra-Low-Power-Modification#1]
Hey,

The reduction of the power consumption in deep sleep is nothing less than awesome. From almost 20mA (milliampere) to almost 0,2mA. Even 2mA I would consider a miricle.

Dr. Keating do you have any data or modifications on the updated version of the the T-Beam? Some time has passed and I think the latest version of the TTGO T-Beam is T22_V1.1 (20210222). They made some changes to the new board compared to the one your modifications are based on.

https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series  with the new schematics.

A decrease in power consumption on the new version would be great! Right now deep sleep lasts with a 3000mAh battery less than 1 week and is kinda unusable in any practical real world application.
I hope there is a miracle coming :)

greetings

**Comment by HikariBoy** [comment]
Glad you liked it,
unfortunately there is no easy answer for the T22_V1.1 as the chipset is considerably different and I would need to identify where the current draw is occuring. The main power chip in the V1.0 was the ME6211 which had an enable pin which could be shut down to lower power consumption, but this has been replaced by the [CP2104](https://www.silabs.com/documents/public/data-sheets/cp2104.pdf) and this chip does not appear to have an enable pin that I can see.  But again, I would need to identify the main current consuming devices on thsi revision.  I would suspect that the hardware redesign in the T22_V1.1 would have addressed some of the background power consumption issues (but I have not looked closely).  The core sleep mode elements in my original post which put the ESP32 into deep-sleep or hibernation should still work I expect.  Just ignore the code that attempts to write to GPIO21 as this controlled the hardware hack I detailed for the V1.0.
